import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { buildReceipt, anchorReceipt } from "./casper-client.mjs";
import {
  createPaymentRequirement,
  encodePaymentHeader,
  signDemoPayment,
  verifyAndSettlePayment
} from "./x402-casper.mjs";
import { recordEvidenceBundle, recordRun } from "./ledger.mjs";

const DATA_PATH = path.join(process.cwd(), "data", "rwa_signals.json");
const AGENT_ID = "cspr-guardian-alpha";
const TOOL_PRICES = {
  "rwa.risk_score": "0.25",
  "rwa.kyb_screen": "0.10",
  "rwa.liquidity_depth": "0.15",
  "rwa.covenant_monitor": "0.12"
};

export async function listTools() {
  return [
    {
      name: "rwa.risk_score",
      title: "Paid RWA Risk Oracle",
      description:
        "Returns KYB, sanctions, liquidity, default-risk, and sizing recommendations for tokenized RWA opportunities.",
      price: "0.25 CSPR",
      payment: "x402-casper",
      inputSchema: {
        type: "object",
        properties: {
          assetId: { type: "string" },
          requestedAmountUsd: { type: "number" }
        },
        required: ["assetId"]
      }
    },
    {
      name: "rwa.kyb_screen",
      title: "Paid KYB and Sanctions Screen",
      description:
        "Checks entity verification status, sanctions exposure, jurisdiction risk, and policy flags before an agent allocates capital.",
      price: "0.10 CSPR",
      payment: "x402-casper",
      inputSchema: {
        type: "object",
        properties: {
          assetId: { type: "string" }
        },
        required: ["assetId"]
      }
    },
    {
      name: "rwa.liquidity_depth",
      title: "Paid Liquidity Depth Oracle",
      description:
        "Reports exit liquidity, slippage estimate, utilization pressure, and max executable allocation for an RWA vault.",
      price: "0.15 CSPR",
      payment: "x402-casper",
      inputSchema: {
        type: "object",
        properties: {
          assetId: { type: "string" },
          requestedAmountUsd: { type: "number" }
        },
        required: ["assetId"]
      }
    },
    {
      name: "rwa.covenant_monitor",
      title: "Paid Covenant Monitor",
      description:
        "Creates a post-allocation monitoring plan with trigger thresholds for repayment, liquidity, and volatility drift.",
      price: "0.12 CSPR",
      payment: "x402-casper",
      inputSchema: {
        type: "object",
        properties: {
          assetId: { type: "string" },
          requestedAmountUsd: { type: "number" }
        },
        required: ["assetId"]
      }
    },
    {
      name: "run.ledger",
      title: "Run Ledger",
      description:
        "Returns historical agent decisions, provider revenue, receipt hashes, and anchor modes for demo auditability.",
      price: "included",
      payment: "casper-receipt",
      inputSchema: {
        type: "object",
        properties: {}
      }
    },
    {
      name: "provider.revenue",
      title: "Provider Revenue Ledger",
      description:
        "Summarizes paid tool revenue generated by autonomous agent calls in the current run.",
      price: "included",
      payment: "casper-receipt",
      inputSchema: {
        type: "object",
        properties: {
          runId: { type: "string" }
        }
      }
    },
    {
      name: "casper.audit_receipt",
      title: "Casper Audit Receipt",
      description:
        "Anchors the final agent decision, payment proof, and risk report hash to Casper testnet.",
      price: "included",
      payment: "casper-deploy",
      inputSchema: {
        type: "object",
        properties: {
          decisionHash: { type: "string" }
        },
        required: ["decisionHash"]
      }
    }
  ];
}

export async function runScenario({ assetId = "invoice-usdc-7d", requestedAmountUsd } = {}) {
  const dataset = await loadSignals();
  const asset = dataset.assets.find((item) => item.id === assetId) || dataset.assets[0];
  const run = {
    id: `run-${crypto.randomUUID()}`,
    startedAt: new Date().toISOString(),
    objective:
      "Autonomously screen an RWA allocation, pay for risk intelligence, and anchor a Casper audit receipt."
  };

  const riskRequirement = buildPaymentRequirement("rwa.risk_score", asset);
  const riskProof = signDemoPayment(riskRequirement, { agentId: AGENT_ID });
  const riskResult = await callPaidRiskOracle({
    assetId: asset.id,
    requestedAmountUsd: requestedAmountUsd || asset.requestedAmountUsd,
    paymentProof: riskProof
  });

  if (riskResult.status !== 200) {
    throw new Error(`Risk oracle failed: ${riskResult.body.error}`);
  }

  const kybRequirement = buildPaymentRequirement("rwa.kyb_screen", asset);
  const kybProof = signDemoPayment(kybRequirement, { agentId: AGENT_ID });
  const kybResult = await callPaidKybOracle({
    assetId: asset.id,
    paymentProof: kybProof
  });

  if (kybResult.status !== 200) {
    throw new Error(`KYB oracle failed: ${kybResult.body.error}`);
  }

  const liquidityRequirement = buildPaymentRequirement("rwa.liquidity_depth", asset);
  const liquidityProof = signDemoPayment(liquidityRequirement, { agentId: AGENT_ID });
  const liquidityResult = await callPaidLiquidityOracle({
    assetId: asset.id,
    requestedAmountUsd: requestedAmountUsd || asset.requestedAmountUsd,
    paymentProof: liquidityProof
  });

  if (liquidityResult.status !== 200) {
    throw new Error(`Liquidity oracle failed: ${liquidityResult.body.error}`);
  }

  const covenantRequirement = buildPaymentRequirement("rwa.covenant_monitor", asset);
  const covenantProof = signDemoPayment(covenantRequirement, { agentId: AGENT_ID });
  const covenantResult = await callPaidCovenantOracle({
    assetId: asset.id,
    requestedAmountUsd: requestedAmountUsd || asset.requestedAmountUsd,
    paymentProof: covenantProof
  });

  if (covenantResult.status !== 200) {
    throw new Error(`Covenant oracle failed: ${covenantResult.body.error}`);
  }

  const riskReport = riskResult.body.report;
  const kybReport = kybResult.body.report;
  const liquidityReport = liquidityResult.body.report;
  const covenantReport = covenantResult.body.report;
  const decision = decide(riskReport, kybReport, liquidityReport, covenantReport);
  const payments = [
    riskResult.body.payment,
    kybResult.body.payment,
    liquidityResult.body.payment,
    covenantResult.body.payment
  ];
  const receipt = buildReceipt({
    agentRun: run,
    payments,
    riskReport,
    kybReport,
    liquidityReport,
    covenantReport,
    decision
  });
  const anchor = await anchorReceipt(receipt);
  const providerRevenue = summarizeProviderRevenue(payments);

  const result = {
    run: {
      ...run,
      completedAt: new Date().toISOString()
    },
    trace: [
      {
        label: "Discover MCP tool",
        status: "complete",
        detail: "Agent found paid risk, KYB, liquidity, and covenant tools with x402-Casper payment requirements."
      },
      {
        label: "Sign x402-Casper payments",
        status: "complete",
        detail: `Ed25519 authorizations signed for ${payments.length} paid tool calls.`
      },
      {
        label: "Settle paid tools",
        status: "complete",
        detail: `${providerRevenue.totalCSPR} CSPR settled across risk, KYB, liquidity, and covenant providers.`,
        txHash: payments.map((item) => item.txHash).join(" | ")
      },
      {
        label: "Call paid risk oracle",
        status: "complete",
        detail: `${asset.name} scored ${riskReport.score}/100 with ${Math.round(riskReport.confidence * 100)}% confidence.`
      },
      {
        label: "Call paid KYB oracle",
        status: "complete",
        detail: `${kybReport.entityStatus} entity, sanctions ${kybReport.sanctionsScreen}, policy ${kybReport.policyResult}.`
      },
      {
        label: "Call paid liquidity oracle",
        status: "complete",
        detail: `${liquidityReport.coverageRatio}x coverage, ${liquidityReport.slippageBps} bps estimated slippage.`
      },
      {
        label: "Call paid covenant monitor",
        status: "complete",
        detail: `${covenantReport.policyResult} monitoring, ${covenantReport.reviewCadenceHours}h review cadence.`
      },
      {
        label: "Make allocation decision",
        status: "complete",
        detail: `${decision.action.toUpperCase()} ${formatUsd(decision.approvedAmountUsd)} at risk tier ${decision.riskTier}.`
      },
      {
        label: "Anchor Casper receipt",
        status: "complete",
        detail: `Receipt hash ${receipt.receiptHash.slice(0, 16)}... anchored.`,
        txHash: anchor.deployHash
      }
    ],
    paymentRequirements: [riskRequirement, kybRequirement, liquidityRequirement, covenantRequirement],
    payments,
    providerRevenue,
    riskReport,
    kybReport,
    liquidityReport,
    covenantReport,
    decision,
    anchor
  };

  result.ledgerEntry = await recordRun(result);
  result.evidenceBundle = await recordEvidenceBundle(result);
  return result;
}

export async function callPaidRiskOracle({ assetId, requestedAmountUsd, paymentProof }) {
  const dataset = await loadSignals();
  const asset = dataset.assets.find((item) => item.id === assetId);

  if (!asset) {
    return { status: 404, body: { error: "Unknown assetId" } };
  }

  if (!paymentProof) {
    const requirement = buildPaymentRequirement("rwa.risk_score", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: "Payment required",
        requirement
      }
    };
  }

  const verification = verifyPayment(asset, "rwa.risk_score", paymentProof);
  if (!verification.isValid) {
    const requirement = buildPaymentRequirement("rwa.risk_score", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: verification.invalidReason,
        requirement
      }
    };
  }

  return {
    status: 200,
    body: {
      report: scoreAsset(asset, requestedAmountUsd || asset.requestedAmountUsd),
      payment: verification.settlement
    }
  };
}

export async function callPaidKybOracle({ assetId, paymentProof }) {
  const dataset = await loadSignals();
  const asset = dataset.assets.find((item) => item.id === assetId);

  if (!asset) {
    return { status: 404, body: { error: "Unknown assetId" } };
  }

  if (!paymentProof) {
    const requirement = buildPaymentRequirement("rwa.kyb_screen", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: "Payment required",
        requirement
      }
    };
  }

  const verification = verifyPayment(asset, "rwa.kyb_screen", paymentProof);
  if (!verification.isValid) {
    const requirement = buildPaymentRequirement("rwa.kyb_screen", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: verification.invalidReason,
        requirement
      }
    };
  }

  return {
    status: 200,
    body: {
      report: buildKybReport(asset),
      payment: verification.settlement
    }
  };
}

export async function callPaidLiquidityOracle({ assetId, requestedAmountUsd, paymentProof }) {
  const dataset = await loadSignals();
  const asset = dataset.assets.find((item) => item.id === assetId);

  if (!asset) {
    return { status: 404, body: { error: "Unknown assetId" } };
  }

  if (!paymentProof) {
    const requirement = buildPaymentRequirement("rwa.liquidity_depth", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: "Payment required",
        requirement
      }
    };
  }

  const verification = verifyPayment(asset, "rwa.liquidity_depth", paymentProof);
  if (!verification.isValid) {
    const requirement = buildPaymentRequirement("rwa.liquidity_depth", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: verification.invalidReason,
        requirement
      }
    };
  }

  return {
    status: 200,
    body: {
      report: buildLiquidityReport(asset, requestedAmountUsd || asset.requestedAmountUsd),
      payment: verification.settlement
    }
  };
}

export async function callPaidCovenantOracle({ assetId, requestedAmountUsd, paymentProof }) {
  const dataset = await loadSignals();
  const asset = dataset.assets.find((item) => item.id === assetId);

  if (!asset) {
    return { status: 404, body: { error: "Unknown assetId" } };
  }

  if (!paymentProof) {
    const requirement = buildPaymentRequirement("rwa.covenant_monitor", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: "Payment required",
        requirement
      }
    };
  }

  const verification = verifyPayment(asset, "rwa.covenant_monitor", paymentProof);
  if (!verification.isValid) {
    const requirement = buildPaymentRequirement("rwa.covenant_monitor", asset);
    return {
      status: 402,
      headers: paymentHeaders(requirement),
      body: {
        error: verification.invalidReason,
        requirement
      }
    };
  }

  return {
    status: 200,
    body: {
      report: buildCovenantReport(asset, requestedAmountUsd || asset.requestedAmountUsd),
      payment: verification.settlement
    }
  };
}

export async function loadSignals() {
  return JSON.parse(await fs.readFile(DATA_PATH, "utf8"));
}

export function evaluatePolicyScenario(asset, requestedAmountUsd = asset.requestedAmountUsd) {
  const riskReport = scoreAsset(asset, requestedAmountUsd);
  const kybReport = buildKybReport(asset);
  const liquidityReport = buildLiquidityReport(asset, requestedAmountUsd);
  const covenantReport = buildCovenantReport(asset, requestedAmountUsd);
  const decision = decide(riskReport, kybReport, liquidityReport, covenantReport);

  return {
    asset,
    requestedAmountUsd,
    riskReport,
    kybReport,
    liquidityReport,
    covenantReport,
    decision
  };
}

function buildPaymentRequirement(tool, asset) {
  const resourceByTool = {
    "rwa.risk_score": "rwa-risk",
    "rwa.kyb_screen": "kyb-screen",
    "rwa.liquidity_depth": "liquidity-depth",
    "rwa.covenant_monitor": "covenant-monitor"
  };
  const descriptionByTool = {
    "rwa.risk_score": `Risk scoring for ${asset.name}`,
    "rwa.kyb_screen": `KYB and sanctions screening for ${asset.name}`,
    "rwa.liquidity_depth": `Liquidity depth and slippage analysis for ${asset.name}`,
    "rwa.covenant_monitor": `Post-allocation covenant monitoring for ${asset.name}`
  };

  return createPaymentRequirement({
    tool,
    assetId: asset.id,
    amount: TOOL_PRICES[tool],
    resource: `/api/oracle/${resourceByTool[tool]}?assetId=${asset.id}`,
    description: descriptionByTool[tool]
  });
}

function scoreAsset(asset, requestedAmountUsd) {
  const health = clamp(asset.counterpartyHealth / 100, 0, 1);
  const liquidity = clamp(asset.liquidityDepthUsd / Math.max(requestedAmountUsd * 5, 1), 0, 1);
  const compliance =
    asset.kybStatus === "verified" && asset.sanctionsScreen === "clear"
      ? 1
      : asset.sanctionsScreen === "clear"
        ? 0.62
        : 0.1;
  const repayment = clamp(1 - asset.latePaymentRate90d * 6, 0, 1);
  const stability = clamp(1 - asset.volatility30d * 8, 0, 1);
  const yieldQuality = clamp(asset.apr / 14, 0, 1);

  const rawScore =
    health * 0.23 +
    liquidity * 0.18 +
    compliance * 0.22 +
    repayment * 0.17 +
    stability * 0.12 +
    yieldQuality * 0.08;

  const score = Math.round(rawScore * 100);
  const maxExposureUsd = Math.round(requestedAmountUsd * clamp(rawScore - 0.08, 0.05, 0.86));

  return {
    asset,
    requestedAmountUsd,
    score,
    confidence: asset.oracleConfidence,
    maxExposureUsd,
    riskTier: score >= 85 ? "A" : score >= 72 ? "B" : score >= 58 ? "C" : "D",
    factors: [
      { label: "Counterparty health", value: Math.round(health * 100) },
      { label: "Liquidity coverage", value: Math.round(liquidity * 100) },
      { label: "Compliance clarity", value: Math.round(compliance * 100) },
      { label: "Repayment history", value: Math.round(repayment * 100) },
      { label: "Market stability", value: Math.round(stability * 100) },
      { label: "Yield quality", value: Math.round(yieldQuality * 100) }
    ],
    warnings: buildWarnings(asset, score)
  };
}

function buildKybReport(asset) {
  const jurisdictionRisk =
    {
      US: "low",
      EU: "low",
      BR: "medium",
      AE: "medium",
      SG: "low"
    }[asset.jurisdiction] || "medium";
  const entityStatus = asset.kybStatus === "verified" ? "verified" : "needs-review";
  const policyResult =
    entityStatus === "verified" && asset.sanctionsScreen === "clear" && jurisdictionRisk !== "high"
      ? "pass"
      : "manual-review";

  return {
    assetId: asset.id,
    entityStatus,
    sanctionsScreen: asset.sanctionsScreen,
    jurisdiction: asset.jurisdiction,
    jurisdictionRisk,
    policyResult,
    reviewedAt: new Date().toISOString(),
    flags: [
      ...(asset.kybStatus === "verified" ? [] : ["KYB document freshness needs review"]),
      ...(asset.sanctionsScreen === "clear" ? [] : ["Sanctions match requires escalation"]),
      ...(jurisdictionRisk === "low" ? [] : [`${asset.jurisdiction} jurisdiction risk is ${jurisdictionRisk}`])
    ]
  };
}

function buildLiquidityReport(asset, requestedAmountUsd) {
  const coverageRatio = asset.liquidityDepthUsd / Math.max(requestedAmountUsd, 1);
  const utilization = clamp(requestedAmountUsd / Math.max(asset.liquidityDepthUsd, 1), 0, 1);
  const slippageBps = Math.round((utilization ** 1.4) * 220 + asset.volatility30d * 1200);
  const exitWindowHours = coverageRatio >= 8 ? 2 : coverageRatio >= 4 ? 8 : coverageRatio >= 2 ? 24 : 72;
  const maxExecutableUsd = Math.round(asset.liquidityDepthUsd * 0.22);
  const liquidityGrade =
    coverageRatio >= 8 && slippageBps <= 65
      ? "A"
      : coverageRatio >= 4 && slippageBps <= 110
        ? "B"
        : coverageRatio >= 2
          ? "C"
          : "D";

  return {
    assetId: asset.id,
    liquidityDepthUsd: asset.liquidityDepthUsd,
    requestedAmountUsd,
    coverageRatio: Number(coverageRatio.toFixed(2)),
    utilization: Number(utilization.toFixed(3)),
    slippageBps,
    exitWindowHours,
    maxExecutableUsd,
    liquidityGrade,
    policyResult: liquidityGrade === "A" || liquidityGrade === "B" ? "pass" : "cap-or-review",
    warnings: [
      ...(coverageRatio < 3 ? ["Requested allocation is large relative to exit liquidity"] : []),
      ...(slippageBps > 120 ? ["Estimated slippage exceeds autonomous policy threshold"] : []),
      ...(exitWindowHours > 24 ? ["Exit window too long for autonomous treasury policy"] : [])
    ]
  };
}

function buildCovenantReport(asset, requestedAmountUsd) {
  const allocationRatio = requestedAmountUsd / Math.max(asset.liquidityDepthUsd, 1);
  const defaultRisk = clamp(asset.latePaymentRate90d * 8 + (100 - asset.counterpartyHealth) / 220, 0, 1);
  const volatilityRisk = clamp(asset.volatility30d * 9, 0, 1);
  const reviewCadenceHours = defaultRisk > 0.55 || volatilityRisk > 0.5 ? 12 : allocationRatio > 0.2 ? 24 : 72;
  const policyResult =
    defaultRisk > 0.72 || volatilityRisk > 0.72
      ? "critical-watch"
      : reviewCadenceHours <= 24
        ? "active-watch"
        : "standard-watch";

  return {
    assetId: asset.id,
    requestedAmountUsd,
    policyResult,
    reviewCadenceHours,
    defaultRisk: Number(defaultRisk.toFixed(3)),
    volatilityRisk: Number(volatilityRisk.toFixed(3)),
    triggers: [
      {
        metric: "latePaymentRate90d",
        current: asset.latePaymentRate90d,
        alertAbove: 0.05
      },
      {
        metric: "liquidityDepthUsd",
        current: asset.liquidityDepthUsd,
        alertBelow: Math.round(requestedAmountUsd * 3)
      },
      {
        metric: "volatility30d",
        current: asset.volatility30d,
        alertAbove: 0.045
      },
      {
        metric: "counterpartyHealth",
        current: asset.counterpartyHealth,
        alertBelow: 70
      }
    ],
    recommendedActions: [
      ...(policyResult === "critical-watch" ? ["Block autonomous execution until reviewer approval"] : []),
      ...(reviewCadenceHours <= 24 ? ["Enable daily covenant checks"] : ["Enable weekly covenant checks"]),
      "Persist monitoring proof with the Casper receipt"
    ]
  };
}

function verifyPayment(asset, tool, paymentProof) {
  return verifyAndSettlePayment(paymentProof, {
    tool,
    assetId: asset.id,
    minAmount: TOOL_PRICES[tool],
    payTo: process.env.CASPER_TREASURY_PUBLIC_KEY || "demo-casper-treasury"
  });
}

function paymentHeaders(requirement) {
  const encoded = encodePaymentHeader(requirement);
  return {
    "PAYMENT-REQUIRED": encoded,
    "X-PAYMENT-REQUIRED": encoded
  };
}

function summarizeProviderRevenue(payments) {
  const total = payments.reduce((sum, item) => sum + Number(item.amount), 0);
  return {
    totalCSPR: total.toFixed(2),
    providers: payments.map((item) => ({
      tool: item.tool,
      amount: item.amount,
      currency: item.currency,
      txHash: item.txHash
    }))
  };
}

function decide(report, kybReport, liquidityReport, covenantReport) {
  const compliancePass = kybReport.policyResult === "pass";
  const liquidityPass = liquidityReport.policyResult === "pass";
  const covenantPass = covenantReport.policyResult !== "critical-watch";
  const executableAmountUsd = Math.min(report.maxExposureUsd, liquidityReport.maxExecutableUsd);

  if (report.score >= 82 && report.confidence >= 0.88 && compliancePass && liquidityPass && covenantPass) {
    return {
      action: "approve",
      riskTier: report.riskTier,
      approvedAmountUsd: executableAmountUsd,
      humanReviewRequired: false,
      rationale:
        "Risk, KYB, liquidity, and covenant policies pass, so the agent can autonomously approve a capped allocation."
    };
  }

  if (report.score >= 68 && report.confidence >= 0.78 && compliancePass && covenantPass) {
    return {
      action: "limit",
      riskTier: report.riskTier,
      approvedAmountUsd: Math.round(executableAmountUsd * 0.55),
      humanReviewRequired: true,
      rationale:
        "The opportunity is viable, but liquidity or risk constraints require capped exposure and reviewer sign-off."
    };
  }

  return {
    action: "reject",
    riskTier: report.riskTier,
    approvedAmountUsd: 0,
    humanReviewRequired: true,
    rationale:
      "Risk-adjusted score or oracle confidence is below the autonomous policy threshold."
  };
}

function buildWarnings(asset, score) {
  const warnings = [];
  if (asset.kybStatus !== "verified") warnings.push("KYB requires manual review");
  if (asset.latePaymentRate90d > 0.05) warnings.push("Elevated 90-day late-payment rate");
  if (asset.liquidityDepthUsd < asset.requestedAmountUsd * 3) warnings.push("Thin exit liquidity");
  if (score < 68) warnings.push("Policy score below autonomous allocation threshold");
  return warnings;
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function formatUsd(value) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0
  }).format(value);
}
